// app/javascript/admin/pages/users/UserDetails.jsx
import React, { useState } from 'react'
import { useParams } from 'react-router-dom'

import { api } from '~/lib/api'
import { useResource, useTitle } from '~/lib/hooks'
import { Alert, Badge, Button, Card, DetailList, EmptyState, ErrorAlert, LoadingBlock, Page, PageHeader } from '~/components/ui'

/** "Ada Lovelace" → "AL". Falls back to "?" so the avatar is never blank. */
function initials(name) {
  const parts = String(name ?? '').trim().split(/\s+/).filter(Boolean)
  if (!parts.length) return '?'
  if (parts.length === 1) return parts[0].charAt(0).toUpperCase()
  return (parts[0].charAt(0) + parts[parts.length - 1].charAt(0)).toUpperCase()
}

function formatDate(value) {
  if (!value) return null
  return new Date(value).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

function formatDateTime(value) {
  if (!value) return null
  return new Date(value).toLocaleString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit',
  })
}

/** The API token, with a copy button. Mirrors the header mobile clients send. */
function ApiTokenPanel({ token }) {
  const [copied, setCopied] = useState(false)
  const [copyError, setCopyError] = useState(null)

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(token)
      setCopyError(null)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      setCopyError('Could not copy to the clipboard. Select the token and copy it manually.')
    }
  }

  return (
    <div className="pt-6 border-t border-line">
      <h2 className="section-title mb-2">API token</h2>
      <div className="flex flex-col sm:flex-row sm:items-center gap-2">
        <code className="flex-1 min-w-0 break-all bg-surface-muted px-3 py-2 rounded-xl text-sm font-mono text-ink select-all">
          {token || 'No token generated'}
        </code>
        {token ? (
          <Button variant="secondary" size="sm" onClick={copy} className="shrink-0">
            {copied ? 'Copied!' : 'Copy'}
          </Button>
        ) : null}
      </div>
      <p className="form-hint mt-2">
        Sent as the <code className="font-mono">x-api-token</code> header by mobile clients.
      </p>
      {copyError ? <Alert tone="error" className="mt-3" onDismiss={() => setCopyError(null)}>{copyError}</Alert> : null}
    </div>
  )
}

export function UserDetails() {
  const { id } = useParams()
  const { data: user, loading, error } = useResource(
    ({ signal }) => api.get(`/api/v1/users/${encodeURIComponent(id)}.json`, { signal }),
    [id]
  )
  useTitle(user?.name || 'User')

  const notFound = error?.status === 404

  return (
    <Page width="max-w-5xl">
      <PageHeader
        title={user?.name || 'User'}
        subtitle="Account information and API access."
        backTo="/users"
        backLabel="Back to users"
      />

      {notFound ? null : <ErrorAlert error={error} className="mb-6" />}

      {loading && !user ? (
        <Card><LoadingBlock label="Loading user…" /></Card>
      ) : notFound ? (
        <EmptyState title="User not found">
          No user matches “{id}”. It may have been deleted, or the link may be out of date.
        </EmptyState>
      ) : user ? (
        <Card className="space-y-6">
          <div className="flex items-center gap-4">
            <div
              className="w-14 h-14 shrink-0 rounded-full bg-primary/10 text-primary flex items-center justify-center"
              aria-hidden="true"
            >
              <span className="font-display font-bold text-xl">{initials(user.name)}</span>
            </div>
            <div className="min-w-0">
              <h2 className="font-display text-lg font-bold text-ink break-words">{user.name || '—'}</h2>
              <p className="text-sm text-ink-muted break-words">{user.email}</p>
            </div>
          </div>

          <div className="pt-6 border-t border-line">
            <DetailList
              items={[
                {
                  label: 'Role',
                  value: <Badge tone={user.role === 'admin' ? 'brand' : 'gray'}>{user.role || 'user'}</Badge>,
                },
                { label: 'User ID', value: user.id },
                { label: 'Slug', value: user.slug },
                { label: 'Sign-ins', value: user.sign_in_count ?? 0 },
                { label: 'Current sign-in', value: formatDateTime(user.current_sign_in_at) },
                { label: 'Previous sign-in', value: formatDateTime(user.last_sign_in_at) },
                { label: 'Current sign-in IP', value: user.current_sign_in_ip },
                { label: 'Previous sign-in IP', value: user.last_sign_in_ip },
                { label: 'Joined', value: formatDate(user.created_at) },
                { label: 'Last updated', value: formatDate(user.updated_at) },
              ]}
            />
          </div>

          <ApiTokenPanel token={user.auth_token} />
        </Card>
      ) : null}
    </Page>
  )
}

// app/javascript/admin/views/UserDetails.vue
<template>
  <div class="p-6 lg:p-10 max-w-7xl mx-auto">
    <div class="page-header">
      <div>
        <h1 class="page-title">User Details</h1>
        <p class="page-subtitle">{{ user.name || 'Account information and API access.' }}</p>
      </div>
      <div class="flex gap-2">
        <router-link :to="{ name: 'users' }" class="btn-secondary">
          Back to Users
        </router-link>
      </div>
    </div>

    <div class="card space-y-6">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <p class="text-xs font-semibold uppercase tracking-wider text-ink-muted mb-1">Name</p>
          <div class="text-ink">{{ user.name || '-' }}</div>
        </div>

        <div>
          <p class="text-xs font-semibold uppercase tracking-wider text-ink-muted mb-1">Email</p>
          <div class="text-ink">{{ user.email || '-' }}</div>
        </div>

        <div>
          <p class="text-xs font-semibold uppercase tracking-wider text-ink-muted mb-1">Role</p>
          <span :class="user.role === 'admin' ? 'badge-brand' : 'badge-gray'">
            {{ user.role || 'user' }}
          </span>
        </div>

        <div>
          <p class="text-xs font-semibold uppercase tracking-wider text-ink-muted mb-1">Created</p>
          <div class="text-ink">{{ formatDate(user.created_at) }}</div>
        </div>
      </div>

      <!-- API Token Section -->
      <div class="pt-6 border-t border-line">
        <p class="text-xs font-semibold uppercase tracking-wider text-ink-muted mb-2">API Token</p>
        <div class="flex items-center gap-2">
          <code class="flex-1 min-w-0 truncate bg-surface-muted px-3 py-2 rounded-xl text-sm font-mono text-ink select-all">
            {{ user.auth_token || 'No token generated' }}
          </code>
          <button
            v-if="user.auth_token"
            type="button"
            @click="copyToken"
            class="btn-secondary btn-sm shrink-0"
          >
            <svg v-if="!copied" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            <svg v-else class="w-4 h-4 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
            </svg>
            {{ copied ? 'Copied!' : 'Copy' }}
          </button>
        </div>
        <p class="form-hint mt-2">
          Use this token in the <code class="bg-surface-muted px-1 py-0.5 rounded font-mono">x-api-token</code> header for API authentication.
        </p>
      </div>
    </div>
  </div>
</template>

<script>
import RestService from "@/services/RestService.js";

export default {
  name: 'UserDetails',
  data() {
    return {
      user: {
        id: null,
        name: '',
        email: '',
        role: '',
        auth_token: '',
        created_at: null,
        updated_at: null,
      },
      copied: false
    }
  },
  mounted() {
    this.loadUser()
  },
  methods: {
    async loadUser() {
      try {
        const service = new RestService('users')
        const response = await service.get(this.$route.params.id)
        this.user = response
      } catch (error) {
        console.error('Error fetching user:', error)
      }
    },
    formatDate(dateString) {
      if (!dateString) return '-'
      return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
      })
    },
    async copyToken() {
      if (!this.user.auth_token) return
      try {
        await navigator.clipboard.writeText(this.user.auth_token)
        this.copied = true
        setTimeout(() => { this.copied = false }, 2000)
      } catch (error) {
        console.error('Failed to copy token:', error)
      }
    }
  }
}
</script>
