// app/javascript/admin/views/features/FeatureForm.vue
<template>
  <div class="p-6 lg:p-10 max-w-7xl mx-auto">
    <div class="page-header">
      <div>
        <h1 class="page-title">{{ isEditing ? 'Edit Feature' : 'New Feature' }}</h1>
        <p class="page-subtitle">Describe the work, set its status and priority, and capture the plan.</p>
      </div>
      <div class="flex gap-2">
        <router-link :to="{ name: 'features' }" class="btn-secondary">
          Back to Features
        </router-link>
      </div>
    </div>

    <form @submit.prevent="handleSubmit" class="max-w-4xl space-y-6">
      <!-- Details -->
      <div class="card">
        <h2 class="section-title mb-4">Details</h2>

        <div class="mb-4">
          <label for="title" class="form-label">Title *</label>
          <input
            id="title"
            v-model="feature.title"
            type="text"
            class="input-form-field"
            placeholder="e.g., Add user authentication"
            required
          >
        </div>

        <div class="mb-4">
          <label for="description" class="form-label">Description</label>
          <textarea
            id="description"
            v-model="feature.description"
            class="input-form-field"
            rows="3"
            placeholder="Brief description of the feature"
          ></textarea>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <div>
            <label for="status" class="form-label">Status</label>
            <select
              id="status"
              v-model="feature.status"
              class="input-form-field"
            >
              <option value="backlog">Backlog</option>
              <option value="planned">Planned</option>
              <option value="in_progress">In Progress</option>
              <option value="completed">Completed</option>
              <option value="cancelled">Cancelled</option>
            </select>
          </div>

          <div>
            <label for="priority" class="form-label">Priority</label>
            <select
              id="priority"
              v-model="feature.priority"
              class="input-form-field"
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
              <option value="critical">Critical</option>
            </select>
          </div>
        </div>

        <div>
          <label for="area" class="form-label">Area</label>
          <input
            id="area"
            v-model="feature.area"
            type="text"
            class="input-form-field"
            placeholder="e.g., Backend, Frontend, API, Infrastructure"
          >
        </div>
      </div>

      <!-- Planning -->
      <div class="card">
        <h2 class="section-title mb-4">Planning</h2>

        <div class="mb-4">
          <label for="acceptance_criteria" class="form-label">Acceptance Criteria</label>
          <textarea
            id="acceptance_criteria"
            v-model="feature.acceptance_criteria"
            class="input-form-field"
            rows="4"
            placeholder="- Criteria 1&#10;- Criteria 2&#10;- Criteria 3"
          ></textarea>
        </div>

        <div class="mb-4">
          <label for="plan" class="form-label">Implementation Plan</label>
          <textarea
            id="plan"
            v-model="feature.plan"
            class="input-form-field"
            rows="4"
            placeholder="High-level plan for implementing this feature"
          ></textarea>
        </div>

        <div>
          <label for="implementation_notes" class="form-label">Implementation Notes</label>
          <textarea
            id="implementation_notes"
            v-model="feature.implementation_notes"
            class="input-form-field"
            rows="4"
            placeholder="Technical notes, decisions made, etc."
          ></textarea>
        </div>
      </div>

      <!-- Timeline -->
      <div class="card">
        <h2 class="section-title mb-4">Timeline</h2>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label for="started_at" class="form-label">Started At</label>
            <input
              id="started_at"
              v-model="feature.started_at"
              type="datetime-local"
              class="input-form-field"
            >
          </div>

          <div>
            <label for="completed_at" class="form-label">Completed At</label>
            <input
              id="completed_at"
              v-model="feature.completed_at"
              type="datetime-local"
              class="input-form-field"
            >
          </div>
        </div>
      </div>

      <!-- Form Actions -->
      <div class="flex gap-3 justify-end">
        <router-link :to="{ name: 'features' }" class="btn-secondary">
          Cancel
        </router-link>
        <button
          type="submit"
          class="btn-primary"
          :disabled="loading"
        >
          {{ loading ? 'Saving...' : (isEditing ? 'Update Feature' : 'Create Feature') }}
        </button>
      </div>
    </form>
  </div>
</template>

<script>
import RestService from '../../../services/RestService.js'

export default {
  name: 'FeatureForm',
  data() {
    return {
      service: new RestService('features', '/'),
      feature: {
        id: null,
        title: '',
        description: '',
        status: 'backlog',
        priority: 'medium',
        area: '',
        acceptance_criteria: '',
        plan: '',
        implementation_notes: '',
        started_at: null,
        completed_at: null
      },
      loading: false
    }
  },
  computed: {
    isEditing() {
      return !!this.feature.id
    }
  },
  mounted() {
    if (this.$route.params.id) {
      this.loadFeature()
    }
  },
  methods: {
    async loadFeature() {
      try {
        const data = await this.service.get(this.$route.params.id)
        this.feature = {
          ...data,
          started_at: this.formatDateForInput(data.started_at),
          completed_at: this.formatDateForInput(data.completed_at)
        }
      } catch (error) {
        console.error('Error loading feature:', error)
      }
    },
    formatDateForInput(dateString) {
      if (!dateString) return null
      const date = new Date(dateString)
      return date.toISOString().slice(0, 16)
    },
    async handleSubmit() {
      try {
        this.loading = true
        const request = { feature: this.feature }

        if (this.isEditing) {
          await this.service.update(this.$route.params.id, request)
        } else {
          await this.service.create(request)
        }

        this.$router.push({ name: 'features' })
      } catch (error) {
        console.error('Error saving feature:', error)
      } finally {
        this.loading = false
      }
    }
  }
}
</script>

// app/javascript/admin/pages/features/FeatureForm.jsx
import React, { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'

import { resource } from '~/lib/api'
import { useMutation, useResource, useTitle } from '~/lib/hooks'
import { Button, Card, ErrorAlert, Field, LoadingBlock, Page, PageHeader } from '~/components/ui'
import { FEATURE_PRIORITIES, FEATURE_STATUSES } from './FeaturesList'

const features = resource('/features')

const BLANK = {
  title: '',
  description: '',
  status: 'backlog',
  priority: 'medium',
  area: '',
  acceptance_criteria: '',
  plan: '',
  implementation_notes: '',
  started_at: '',
  completed_at: '',
}

/** ISO timestamp from Rails → the `YYYY-MM-DD` a date input wants. */
function toDateInput(value) {
  return value ? String(value).slice(0, 10) : ''
}

export function FeatureForm() {
  const { id } = useParams()
  const navigate = useNavigate()
  const editing = !!id
  useTitle(editing ? 'Edit feature' : 'New feature')

  const [form, setForm] = useState(BLANK)
  const set = (key) => (value) => setForm((current) => ({ ...current, [key]: value }))

  const { data, loading, error } = useResource(
    ({ signal }) => (id ? features.get(id, { signal }) : Promise.resolve(null)),
    [id]
  )

  useEffect(() => {
    if (!data) return
    setForm({
      title: data.title ?? '',
      description: data.description ?? '',
      status: data.status ?? 'backlog',
      priority: data.priority ?? 'medium',
      area: data.area ?? '',
      acceptance_criteria: data.acceptance_criteria ?? '',
      plan: data.plan ?? '',
      implementation_notes: data.implementation_notes ?? '',
      started_at: toDateInput(data.started_at),
      completed_at: toDateInput(data.completed_at),
    })
  }, [data])

  const { run: save, pending, error: saveError } = useMutation((payload) =>
    editing ? features.update(id, payload) : features.create(payload)
  )

  const fieldErrors = saveError?.fieldErrors ?? {}
  const fieldError = (key) => {
    const messages = fieldErrors[key]
    if (!messages) return undefined
    return Array.isArray(messages) ? messages.join(', ') : String(messages)
  }

  const submit = async (event) => {
    event.preventDefault()
    const result = await save({
      feature: {
        ...form,
        started_at: form.started_at || null,
        completed_at: form.completed_at || null,
      },
    })
    if (result !== null) navigate('/features')
  }

  return (
    <Page width="max-w-3xl">
      <PageHeader
        title={editing ? 'Edit feature' : 'New feature'}
        subtitle="Describe the work, set its status and priority, and capture the plan."
        backTo="/features"
        backLabel="Back to features"
      />

      <ErrorAlert error={error} className="mb-6" />
      <ErrorAlert error={saveError} className="mb-6" />

      {editing && loading && !data ? (
        <Card><LoadingBlock label="Loading feature…" /></Card>
      ) : (
        <form onSubmit={submit} className="space-y-6">
          <Card>
            <h2 className="section-title mb-4">Details</h2>
            <div className="space-y-4">
              <Field
                label="Title"
                value={form.title}
                onChange={set('title')}
                placeholder="e.g. Add user authentication"
                error={fieldError('title')}
                required
              />
              <Field
                label="Description"
                as="textarea"
                rows={3}
                value={form.description}
                onChange={set('description')}
                placeholder="Brief description of the feature"
                error={fieldError('description')}
              />
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <Field
                  label="Status"
                  as="select"
                  value={form.status}
                  onChange={set('status')}
                  options={FEATURE_STATUSES}
                  error={fieldError('status')}
                />
                <Field
                  label="Priority"
                  as="select"
                  value={form.priority}
                  onChange={set('priority')}
                  options={FEATURE_PRIORITIES}
                  error={fieldError('priority')}
                />
              </div>
              <Field
                label="Area"
                value={form.area}
                onChange={set('area')}
                placeholder="e.g. Backend, Frontend, API, Infrastructure"
                error={fieldError('area')}
              />
            </div>
          </Card>

          <Card>
            <h2 className="section-title mb-4">Planning</h2>
            <div className="space-y-4">
              <Field
                label="Acceptance criteria"
                as="textarea"
                rows={4}
                value={form.acceptance_criteria}
                onChange={set('acceptance_criteria')}
                placeholder={'- Criteria 1\n- Criteria 2'}
                error={fieldError('acceptance_criteria')}
              />
              <Field
                label="Implementation plan"
                as="textarea"
                rows={4}
                value={form.plan}
                onChange={set('plan')}
                placeholder="High-level plan for implementing this feature"
                error={fieldError('plan')}
              />
              <Field
                label="Implementation notes"
                as="textarea"
                rows={4}
                value={form.implementation_notes}
                onChange={set('implementation_notes')}
                placeholder="Technical notes, decisions made, etc."
                error={fieldError('implementation_notes')}
              />
            </div>
          </Card>

          <Card>
            <h2 className="section-title mb-4">Timeline</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Field
                label="Started"
                type="date"
                value={form.started_at}
                onChange={set('started_at')}
                error={fieldError('started_at')}
              />
              <Field
                label="Completed"
                type="date"
                value={form.completed_at}
                onChange={set('completed_at')}
                error={fieldError('completed_at')}
              />
            </div>
          </Card>

          <div className="flex flex-col-reverse sm:flex-row sm:justify-end gap-3">
            <Button variant="secondary" to="/features">Cancel</Button>
            <Button type="submit" loading={pending}>{editing ? 'Update feature' : 'Create feature'}</Button>
          </div>
        </form>
      )}
    </Page>
  )
}
