// app/javascript/admin/pages/funnels/FunnelMetrics.jsx
import React, { useState } from 'react'

import { api } from '~/lib/api'
import { useResource, useTitle } from '~/lib/hooks'
import { Button, Card, ErrorAlert, Field, LoadingBlock, Page, PageHeader, StatTile, Toolbar } from '~/components/ui'

/**
 * GET /api/v1/funnels/metrics.json returns:
 *   { funnels: [{ id, name, slug }],                       // active funnels, for the filter
 *     metrics: { lead_page, book_call_page,
 *                order_page, order_completed_page },       // ahoy funnel_page_view counts
 *     conversion_rates: { lead_to_book_call, book_call_to_order,
 *                         order_to_completed, overall },   // percentages, 2dp, 0 when the
 *                                                          // denominator is 0
 *     filters: { funnel_slug, start_date, end_date } }
 *
 * The server can't distinguish "0% converted" from "nothing to divide by", so
 * every rate below is re-guarded against its own denominator and rendered as —.
 */

const EMPTY_METRICS = { lead_page: 0, book_call_page: 0, order_page: 0, order_completed_page: 0 }

const STAGES = [
  { key: 'lead_page', label: 'Lead page' },
  { key: 'book_call_page', label: 'Book call page' },
  { key: 'order_page', label: 'Order page' },
  { key: 'order_completed_page', label: 'Order completed' },
]

const RATES = [
  { key: 'lead_to_book_call', label: 'Lead → Book call', denominator: 'lead_page' },
  { key: 'book_call_to_order', label: 'Book call → Order', denominator: 'book_call_page' },
  { key: 'order_to_completed', label: 'Order → Completed', denominator: 'order_page' },
  { key: 'overall', label: 'Lead → Order completed', denominator: 'lead_page' },
]

function percentOf(part, whole) {
  if (!whole) return null
  return (part / whole) * 100
}

export function FunnelMetrics() {
  useTitle('Funnel metrics')

  const [funnelSlug, setFunnelSlug] = useState('')
  const [startDate, setStartDate] = useState('')
  const [endDate, setEndDate] = useState('')

  const { data, loading, error } = useResource(({ signal }) => {
    const params = new URLSearchParams()
    if (funnelSlug) params.set('funnel_slug', funnelSlug)
    if (startDate) params.set('start_date', startDate)
    if (endDate) params.set('end_date', endDate)
    const query = params.toString()
    return api.get(`/api/v1/funnels/metrics.json${query ? `?${query}` : ''}`, { signal })
  }, [funnelSlug, startDate, endDate])

  const metrics = data?.metrics ?? EMPTY_METRICS
  const rates = data?.conversion_rates ?? {}
  const funnels = data?.funnels ?? []
  const leads = metrics.lead_page ?? 0

  const clearFilters = () => {
    setFunnelSlug('')
    setStartDate('')
    setEndDate('')
  }

  const hasFilters = !!(funnelSlug || startDate || endDate)

  return (
    <Page>
      <PageHeader
        title="Funnel metrics"
        subtitle="Page views at each stage and how many visitors move on."
        backTo="/funnels"
        backLabel="Back to funnels"
      />

      <Toolbar>
        <Field
          label="Funnel"
          as="select"
          value={funnelSlug}
          onChange={setFunnelSlug}
          options={[['', 'All funnels'], ...funnels.map((funnel) => [funnel.slug, funnel.name])]}
          className="min-w-0 flex-1 sm:flex-none"
          inputClassName="sm:w-auto"
        />
        <Field label="Start date" type="date" value={startDate} onChange={setStartDate} className="min-w-0 flex-1 sm:flex-none" />
        <Field label="End date" type="date" value={endDate} onChange={setEndDate} className="min-w-0 flex-1 sm:flex-none" />
        {hasFilters ? <Button variant="ghost" onClick={clearFilters}>Clear</Button> : null}
      </Toolbar>

      <ErrorAlert error={error} className="mb-6" />

      {loading && !data ? (
        <Card><LoadingBlock label="Loading metrics…" /></Card>
      ) : (
        <div className="space-y-6">
          <div className="grid gap-4 grid-cols-2 lg:grid-cols-4">
            {STAGES.map((stage) => {
              const share = percentOf(metrics[stage.key] ?? 0, leads)
              return (
                <StatTile
                  key={stage.key}
                  label={stage.label}
                  value={metrics[stage.key] ?? 0}
                  hint={stage.key === 'lead_page' || share === null ? undefined : `${Math.round(share)}% of leads`}
                />
              )
            })}
          </div>

          <Card>
            <h2 className="section-title mb-4">Conversion rates</h2>
            <ul className="space-y-3">
              {RATES.map((rate) => {
                // 0 views at the previous stage means the rate is undefined, not 0%.
                const measurable = (metrics[rate.denominator] ?? 0) > 0
                const value = Number(rates[rate.key] ?? 0)
                const width = measurable ? Math.min(100, Math.max(0, value)) : 0
                return (
                  <li key={rate.key}>
                    <div className="flex items-baseline justify-between gap-3 mb-1">
                      <span className="text-sm text-ink truncate min-w-0">{rate.label}</span>
                      <span className="text-sm font-medium text-ink-muted shrink-0 tabular-nums">
                        {measurable ? `${value}%` : '—'}
                      </span>
                    </div>
                    <div className="h-1.5 rounded-full bg-surface-muted overflow-hidden">
                      <div className="h-full rounded-full bg-primary" style={{ width: `${width}%` }} />
                    </div>
                  </li>
                )
              })}
            </ul>
            {!leads ? (
              <p className="text-sm text-ink-muted mt-4">
                No funnel page views recorded for this selection yet.
              </p>
            ) : null}
          </Card>
        </div>
      )}
    </Page>
  )
}

// app/javascript/admin/views/funnels/FunnelMetrics.vue
<template>
  <div class="p-6 lg:p-10 max-w-7xl mx-auto">
    <div class="page-header">
      <div>
        <h1 class="page-title">Funnel Metrics</h1>
        <p class="page-subtitle">Page views at each stage and how many visitors move on.</p>
      </div>
      <div class="flex gap-2">
        <router-link :to="{ name: 'funnels' }" class="btn-secondary">
          Back to Funnels
        </router-link>
      </div>
    </div>

    <!-- Filters -->
    <div class="card flex flex-wrap items-end gap-4 mb-6">
      <div>
        <label class="form-label">Funnel</label>
        <select v-model="filters.funnelSlug" @change="fetchMetrics" class="input-form-field w-auto min-w-48">
          <option value="">All Funnels</option>
          <option v-for="funnel in funnels" :key="funnel.id" :value="funnel.slug">
            {{ funnel.name }}
          </option>
        </select>
      </div>
      <div>
        <label class="form-label">Start Date</label>
        <input type="date" v-model="filters.startDate" @change="fetchMetrics" class="input-form-field w-auto">
      </div>
      <div>
        <label class="form-label">End Date</label>
        <input type="date" v-model="filters.endDate" @change="fetchMetrics" class="input-form-field w-auto">
      </div>
      <button type="button" @click="clearFilters" class="btn-ghost">
        Clear
      </button>
    </div>

    <!-- Stage totals -->
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-6">
      <div class="stat-tile">
        <p class="stat-label">Lead Page</p>
        <p class="stat-value">{{ metrics.lead_page }}</p>
      </div>
      <div class="stat-tile">
        <p class="stat-label">Book Call Page</p>
        <p class="stat-value">{{ metrics.book_call_page }}</p>
      </div>
      <div class="stat-tile">
        <p class="stat-label">Order Page</p>
        <p class="stat-value">{{ metrics.order_page }}</p>
      </div>
      <div class="stat-tile">
        <p class="stat-label">Order Completed</p>
        <p class="stat-value text-emerald-600">{{ metrics.order_completed_page }}</p>
      </div>
    </div>

    <!-- Conversion by stage -->
    <div class="card-flush overflow-x-auto">
      <div class="flex flex-wrap items-center justify-between gap-3 px-6 py-4 border-b border-line">
        <h2 class="section-title">Conversion Funnel</h2>
        <div class="text-right">
          <p class="eyebrow">Overall conversion</p>
          <p class="font-display text-2xl font-extrabold text-primary leading-tight">{{ conversionRates.overall }}%</p>
          <p class="text-xs text-ink-muted">Lead Page to Order Completed</p>
        </div>
      </div>
      <table class="admin-table">
        <thead>
          <tr>
            <th>Stage</th>
            <th>Views</th>
            <th>From previous</th>
            <th class="w-1/2">Share of leads</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="font-medium whitespace-nowrap">Lead Page</td>
            <td class="font-semibold">{{ metrics.lead_page }}</td>
            <td class="text-ink-muted">-</td>
            <td>
              <div class="h-3 rounded-full bg-primary/10 overflow-hidden">
                <div class="h-3 rounded-full bg-primary" style="width: 100%"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="font-medium whitespace-nowrap">Book Call Page</td>
            <td class="font-semibold">{{ metrics.book_call_page }}</td>
            <td><span class="badge-brand">{{ conversionRates.lead_to_book_call }}%</span></td>
            <td>
              <div class="h-3 rounded-full bg-primary/10 overflow-hidden">
                <div class="h-3 rounded-full bg-primary/80" :style="{ width: calculateWidth('book_call_page') }"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="font-medium whitespace-nowrap">Order Page</td>
            <td class="font-semibold">{{ metrics.order_page }}</td>
            <td><span class="badge-brand">{{ conversionRates.book_call_to_order }}%</span></td>
            <td>
              <div class="h-3 rounded-full bg-primary/10 overflow-hidden">
                <div class="h-3 rounded-full bg-primary/60" :style="{ width: calculateWidth('order_page') }"></div>
              </div>
            </td>
          </tr>
          <tr>
            <td class="font-medium whitespace-nowrap">Order Completed</td>
            <td class="font-semibold text-emerald-600">{{ metrics.order_completed_page }}</td>
            <td><span class="badge-green">{{ conversionRates.order_to_completed }}%</span></td>
            <td>
              <div class="h-3 rounded-full bg-primary/10 overflow-hidden">
                <div class="h-3 rounded-full bg-emerald-500" :style="{ width: calculateWidth('order_completed_page') }"></div>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script>
import RestService from '../../../services/RestService.js'

export default {
  name: 'FunnelMetrics',
  data() {
    return {
      model: starter.model,
      funnels: [],
      metrics: {
        lead_page: 0,
        book_call_page: 0,
        order_page: 0,
        order_completed_page: 0
      },
      conversionRates: {
        lead_to_book_call: 0,
        book_call_to_order: 0,
        order_to_completed: 0,
        overall: 0
      },
      filters: {
        funnelSlug: '',
        startDate: '',
        endDate: ''
      }
    }
  },
  mounted() {
    this.fetchFunnels()
    this.fetchMetrics()
  },
  methods: {
    async fetchFunnels() {
      try {
        const service = new RestService('funnels')
        this.funnels = await service.list()
      } catch (error) {
        console.error('Error fetching funnels:', error)
      }
    },
    async fetchMetrics() {
      try {
        this.model.loading = true
        const params = new URLSearchParams()
        if (this.filters.funnelSlug) params.append('funnel_slug', this.filters.funnelSlug)
        if (this.filters.startDate) params.append('start_date', this.filters.startDate)
        if (this.filters.endDate) params.append('end_date', this.filters.endDate)

        const url = `/api/v1/funnels/metrics.json?${params.toString()}&t=${Date.now()}`
        const response = await fetch(url, {
          headers: {
            'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]')?.content
          }
        })
        const data = await response.json()

        this.metrics = data.metrics
        this.conversionRates = data.conversion_rates
      } catch (error) {
        console.error('Error fetching metrics:', error)
      } finally {
        this.model.loading = false
      }
    },
    calculateWidth(stage) {
      if (this.metrics.lead_page === 0) return '0%'
      const percentage = (this.metrics[stage] / this.metrics.lead_page) * 100
      return `${Math.max(percentage, 5)}%`
    },
    clearFilters() {
      this.filters = { funnelSlug: '', startDate: '', endDate: '' }
      this.fetchMetrics()
    }
  }
}
</script>
