// app/javascript/admin/pages/logs/LogSubscriptions.jsx
import React, { useState } from 'react'

import { api, resource } from '~/lib/api'
import { useFlash, useMutation, useResource, useTitle } from '~/lib/hooks'
import {
  Alert, Badge, BoolBadge, Button, Card, ConfirmModal, DataTable, ErrorAlert, Field, Page, PageHeader,
} from '~/components/ui'

const subscriptions = resource('/log-subscriptions')

/** LogSubscription::CHANNELS. */
const CHANNELS = [['email', 'Email'], ['slack', 'Slack']]

/** Log::LEVELS — the notification fires at this level or above. */
const LEVELS = [['info', 'Info'], ['warn', 'Warn'], ['error', 'Error'], ['fatal', 'Fatal']]

const BLANK = {
  id: null,
  name: '',
  channel: 'email',
  destination: '',
  min_level: 'error',
  throttle_minutes: 60,
  active: true,
}

export function LogSubscriptions() {
  useTitle('Log notifications')

  const [editing, setEditing] = useState(null)
  const [pendingDelete, setPendingDelete] = useState(null)
  const [flash, setFlash] = useFlash()

  const { data, loading, error, reload } = useResource(({ signal }) => subscriptions.list('', { signal }), [])
  const rows = data ?? []

  const { run: save, pending: saving, error: saveError, setError: setSaveError } = useMutation((subscription) => {
    const payload = {
      log_subscription: {
        name: subscription.name,
        channel: subscription.channel,
        destination: subscription.destination,
        min_level: subscription.min_level,
        throttle_minutes: subscription.throttle_minutes,
        active: subscription.active,
      },
    }
    return subscription.id ? subscriptions.update(subscription.id, payload) : subscriptions.create(payload)
  })
  const { run: destroy, error: deleteError } = useMutation((subscription) => subscriptions.remove(subscription.id))
  const { run: sendTest, pending: testing, error: testError, setError: setTestError } = useMutation((subscription) =>
    api.post(`/log-subscriptions/${subscription.id}/test.json`)
  )

  const fieldErrors = saveError?.fieldErrors ?? {}
  const fieldError = (key) => {
    const messages = fieldErrors[key]
    if (!messages) return undefined
    return Array.isArray(messages) ? messages.join(', ') : String(messages)
  }

  const set = (key) => (value) => setEditing((current) => ({ ...current, [key]: value }))

  const startNew = () => { setSaveError(null); setEditing({ ...BLANK }) }
  const startEdit = (subscription) => { setSaveError(null); setEditing({ ...BLANK, ...subscription }) }

  const submit = async (event) => {
    event.preventDefault()
    const result = await save(editing)
    if (result === null) return
    setEditing(null)
    setFlash({ tone: 'success', message: 'Notification saved.' })
    reload()
  }

  const onDelete = async () => {
    const target = pendingDelete
    setPendingDelete(null)
    if ((await destroy(target)) === null) return
    setFlash({ tone: 'success', message: 'Notification deleted.' })
    reload()
  }

  const onTest = async (subscription) => {
    setTestError(null)
    const result = await sendTest(subscription)
    if (result === null) return
    setFlash({ tone: 'success', message: result.message || 'Test notification sent.' })
    reload()
  }

  const slack = editing?.channel === 'slack'

  const columns = [
    {
      key: 'name',
      header: 'Name',
      primary: true,
      render: (row) => row.name || row.display_name || '—',
    },
    { key: 'channel', header: 'Channel', render: (row) => <Badge tone="brand">{row.channel}</Badge> },
    { key: 'destination', header: 'Destination', wide: true, render: (row) => <span className="break-all">{row.destination}</span> },
    { key: 'min_level', header: 'Level', render: (row) => <Badge tone="gray">{`${row.min_level}+`}</Badge> },
    { key: 'throttle_minutes', header: 'Throttle', render: (row) => `${row.throttle_minutes}m` },
    { key: 'active', header: 'Status', render: (row) => <BoolBadge value={row.active} yes="Active" no="Paused" /> },
  ]

  return (
    <Page width="max-w-5xl">
      <PageHeader
        title="Log notifications"
        subtitle="Who gets told when something lands in the log, and how."
        backTo="/logs"
        backLabel="Back to logs"
      >
        <Button onClick={startNew}>New notification</Button>
      </PageHeader>

      {flash ? (
        <Alert tone={flash.tone} className="mb-6" onDismiss={() => setFlash(null)}>{flash.message}</Alert>
      ) : null}

      <ErrorAlert error={error} className="mb-6" />
      <ErrorAlert error={testError} className="mb-6" />
      <ErrorAlert error={deleteError} className="mb-6" />

      {editing ? (
        <Card className="mb-6">
          <form onSubmit={submit}>
            <h2 className="section-title mb-4">{editing.id ? 'Edit notification' : 'New notification'}</h2>

            <ErrorAlert error={saveError} className="mb-4" />

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <Field
                label="Name"
                value={editing.name ?? ''}
                onChange={set('name')}
                placeholder="Ops on-call"
                hint="Optional label so you can tell rules apart."
                error={fieldError('name')}
              />
              <Field
                label="Channel"
                as="select"
                value={editing.channel}
                onChange={set('channel')}
                options={CHANNELS}
                error={fieldError('channel')}
              />
              <Field
                className="sm:col-span-2"
                label="Destination"
                value={editing.destination ?? ''}
                onChange={set('destination')}
                placeholder={slack ? 'https://hooks.slack.com/services/…' : 'ops@example.com'}
                hint={slack
                  ? 'A Slack incoming-webhook URL — it must start with https://hooks.slack.com/.'
                  : 'An email address. Requires outgoing mail to be configured.'}
                error={fieldError('destination')}
              />
              <Field
                label="Notify at or above"
                as="select"
                value={editing.min_level}
                onChange={set('min_level')}
                options={LEVELS}
                hint="Error is the sensible default. Info will be noisy."
                error={fieldError('min_level')}
              />
              <Field
                label="Throttle (minutes)"
                type="number"
                min="0"
                max="10080"
                value={editing.throttle_minutes ?? 0}
                onChange={(value) => set('throttle_minutes')(value === '' ? '' : Number(value))}
                hint="Minimum gap before the same recurring problem notifies again."
                error={fieldError('throttle_minutes')}
              />
              <Field
                className="sm:col-span-2"
                label="Active"
                type="checkbox"
                value={editing.active}
                onChange={set('active')}
                hint="Paused rules stay configured but never notify."
              />
            </div>

            <div className="flex flex-col-reverse sm:flex-row sm:justify-end gap-3 mt-6">
              <Button variant="secondary" type="button" onClick={() => setEditing(null)}>Cancel</Button>
              <Button type="submit" loading={saving}>Save</Button>
            </div>
          </form>
        </Card>
      ) : null}

      <DataTable
        columns={columns}
        rows={rows}
        rowKey={(row) => row.id}
        actions={(row) => (
          <>
            <Button size="sm" variant="ghost" disabled={testing} onClick={() => onTest(row)} title="Send a test notification">
              Test
            </Button>
            <Button size="sm" variant="ghost" onClick={() => startEdit(row)}>Edit</Button>
            <Button size="sm" variant="ghost" className="text-red-600" onClick={() => setPendingDelete(row)}>Delete</Button>
          </>
        )}
        empty="No notifications yet. Add one so errors reach a human."
        loading={loading}
        caption="Log notification rules"
      />

      <ConfirmModal
        open={!!pendingDelete}
        title="Delete this notification?"
        message="Nobody will be notified through this channel any more."
        confirmText="Delete"
        tone="danger"
        onConfirm={onDelete}
        onCancel={() => setPendingDelete(null)}
      />
    </Page>
  )
}

// app/javascript/admin/views/logs/LogSubscriptions.vue
<template>
  <div class="p-6 lg:p-10 max-w-5xl mx-auto">
    <router-link :to="{ name: 'logs' }" class="text-sm text-ink-muted hover:text-primary">← Back to logs</router-link>

    <div class="page-header mt-4">
      <div>
        <h1 class="page-title">Log notifications</h1>
        <p class="page-subtitle">Who gets told when something lands in the log, and how.</p>
      </div>
      <button class="btn-primary" @click="startNew()">New notification</button>
    </div>

    <div v-if="flash.message" :class="flash.ok ? 'alert-success' : 'alert-error'" class="mb-6">{{ flash.message }}</div>

    <!-- Form -->
    <form v-if="editing" class="card mb-6" @submit.prevent="save()">
      <h2 class="section-title mb-4">{{ editing.id ? 'Edit notification' : 'New notification' }}</h2>

      <div v-if="errors.length" class="alert-error mb-4">
        <ul class="list-disc list-inside">
          <li v-for="(error, index) in errors" :key="index">{{ error }}</li>
        </ul>
      </div>

      <div class="grid gap-4 sm:grid-cols-2">
        <div>
          <label class="form-label" for="subName">Name</label>
          <input id="subName" type="text" class="input-form-field" v-model="editing.name" placeholder="Ops on-call">
          <p class="form-hint">Optional label so you can tell rules apart.</p>
        </div>

        <div>
          <label class="form-label" for="subChannel">Channel</label>
          <select id="subChannel" class="input-form-field" v-model="editing.channel">
            <option value="email">Email</option>
            <option value="slack">Slack</option>
          </select>
        </div>

        <div class="sm:col-span-2">
          <label class="form-label" for="subDestination">Destination</label>
          <input id="subDestination" type="text" class="input-form-field" v-model="editing.destination"
                 :placeholder="editing.channel === 'slack' ? 'https://hooks.slack.com/services/…' : 'ops@example.com'">
          <p class="form-hint">
            {{ editing.channel === 'slack' ? 'A Slack incoming-webhook URL.' : 'An email address. Requires outgoing mail to be configured.' }}
          </p>
        </div>

        <div>
          <label class="form-label" for="subLevel">Notify at or above</label>
          <select id="subLevel" class="input-form-field" v-model="editing.min_level">
            <option value="info">Info</option>
            <option value="warn">Warn</option>
            <option value="error">Error</option>
            <option value="fatal">Fatal</option>
          </select>
          <p class="form-hint">Error is the sensible default. Info will be noisy.</p>
        </div>

        <div>
          <label class="form-label" for="subThrottle">Throttle (minutes)</label>
          <input id="subThrottle" type="number" min="0" max="10080" class="input-form-field" v-model.number="editing.throttle_minutes">
          <p class="form-hint">Minimum gap before the same recurring problem notifies again.</p>
        </div>

        <div class="sm:col-span-2">
          <label class="flex items-center gap-2 text-sm">
            <input type="checkbox" class="form-checkbox" v-model="editing.active">
            Active
          </label>
        </div>
      </div>

      <div class="flex gap-3 justify-end mt-6">
        <button type="button" class="btn-secondary" @click="editing = null">Cancel</button>
        <button type="submit" class="btn-primary">Save</button>
      </div>
    </form>

    <!-- List -->
    <div class="card-flush overflow-x-auto">
      <table class="admin-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Channel</th>
            <th>Destination</th>
            <th>Level</th>
            <th>Throttle</th>
            <th>Status</th>
            <th><span class="sr-only">Actions</span></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="subscription in subscriptions" :key="subscription.id">
            <td>{{ subscription.name || '—' }}</td>
            <td><span class="badge-brand">{{ subscription.channel }}</span></td>
            <td class="break-all">{{ subscription.destination }}</td>
            <td><span class="badge-gray">{{ subscription.min_level }}+</span></td>
            <td>{{ subscription.throttle_minutes }}m</td>
            <td>
              <span :class="subscription.active ? 'badge-green' : 'badge-gray'">
                {{ subscription.active ? 'Active' : 'Paused' }}
              </span>
            </td>
            <td>
              <div class="flex justify-end gap-1">
                <button class="btn-ghost btn-sm" title="Send a test notification" @click="sendTest(subscription)">Test</button>
                <button class="btn-ghost btn-sm" @click="edit(subscription)">Edit</button>
                <button class="btn-ghost btn-sm" @click="confirmDelete = subscription">Delete</button>
              </div>
            </td>
          </tr>
          <tr v-if="!subscriptions.length">
            <td colspan="7" class="empty-state">
              No notifications yet. Add one so errors reach a human.
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <confirm-modal
      v-if="confirmDelete"
      title="Delete this notification?"
      message="Nobody will be notified through this channel any more."
      confirm-text="Delete"
      confirm-style="danger"
      @confirm="destroy(confirmDelete)"
      @cancel="confirmDelete = null" />
  </div>
</template>

<script>
import RestService from '../../../services/RestService'
import ConfirmModal from '../../../components/ConfirmModal.vue'

const BLANK = {
  id: null, name: '', channel: 'email', destination: '',
  min_level: 'error', active: true, throttle_minutes: 60
}

export default {
  name: 'LogSubscriptions',
  components: { ConfirmModal },
  data () {
    return {
      model: starter.model,
      service: new RestService('log-subscriptions', '/'),
      subscriptions: [],
      editing: null,
      errors: [],
      flash: { message: '', ok: true },
      confirmDelete: null
    }
  },
  mounted () {
    this.load()
  },
  methods: {
    load () {
      this.model.loading = true
      this.service.list().then((response) => {
        this.subscriptions = response
        this.model.loading = false
      }).catch((message) => {
        console.log('error loading log subscriptions')
        console.log(message)
        this.model.loading = false
      })
    },

    startNew () {
      this.errors = []
      this.editing = Object.assign({}, BLANK)
    },

    edit (subscription) {
      this.errors = []
      this.editing = Object.assign({}, subscription)
    },

    save () {
      this.errors = []
      const payload = { log_subscription: this.editing }
      const request = this.editing.id
        ? this.service.update(this.editing.id, payload)
        : this.service.create(payload)

      request.then(() => {
        this.editing = null
        this.setFlash('Notification saved.', true)
        this.load()
      }).catch((response) => {
        this.errors = this.extractErrors(response)
      })
    },

    destroy (subscription) {
      this.confirmDelete = null
      this.service.remove(subscription.id).then(() => {
        this.setFlash('Notification deleted.', true)
        this.load()
      }).catch((message) => {
        console.log('error deleting log subscription')
        console.log(message)
      })
    },

    sendTest (subscription) {
      this.model.loading = true
      this.service.executeEmptyPost(`/log-subscriptions/${subscription.id}/test.json`).then((response) => {
        this.setFlash(response.message || 'Test notification sent.', true)
        this.model.loading = false
        this.load()
      }).catch((response) => {
        this.setFlash((response && response.error) || 'Test notification failed.', false)
        this.model.loading = false
      })
    },

    extractErrors (response) {
      const errors = response && response.errors
      if (!errors) return ['Could not save. Check the fields and try again.']
      if (Array.isArray(errors)) return errors
      return Object.entries(errors).map(([field, messages]) => {
        const text = Array.isArray(messages) ? messages.join(', ') : messages
        return `${field.replace(/_/g, ' ')} ${text}`
      })
    },

    setFlash (message, ok) {
      this.flash = { message, ok }
      setTimeout(() => { this.flash = { message: '', ok: true } }, 6000)
    }
  }
}
</script>
